### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by mjg59** [martinjungblut/go-cryptsetup#1]
Hi! I'd like to make use of this, but there's no explicit license attached to it. Would it be possible to add one?

**Comment by martinjungblut** [comment]
Hi there mjg59.

Sure thing, I think forgot to add it when I made the repository! There it is, BSD 2-clause licence. Feel free to use on proprietary projects or whatever you need.

May I ask you a favour in return? If you feel there's some feature missing, or if you find any undesired behaviour, could you please report them?

I intend to finish the "To-do" list on this library in the next few days.

**Comment by mjg59** [comment]
Thanks! Just sent you a PR that adds the basic functionality needed for my usecase.
