### ISSUE TITLE
Support tcryptDump_with_volume_key

### ISSUE THREAD

**Issue by tracefinder** [martinjungblut/go-cryptsetup#5]
Hi.
First of all, thank you for the project. It really helps.
Secondly, I want to implement key dump in a way cryptsetup does in [tcryptDump_with_volume_key](https://gitlab.com/cryptsetup/cryptsetup/-/blob/78797ae078604f268e6b1f4af5ad2121f9dc0ae5/src/cryptsetup.c#L541).
A working code snippet looks like this
```go
// VolumeKeyGet gets volume key from crypt device.
// Returns unlocked key slot number or negative errno otherwise.
// C equivalent: crypt_volume_key_get
func (device *Device) VolumeKeyGet(keyslot int, passphrase string) ([]byte, error) {
	cPassphrase := C.CString(passphrase)
	defer C.free(unsafe.Pointer(cPassphrase))

	cVKSize := C.crypt_get_volume_key_size(device.cryptDevice)
	cVKPointer := C.crypt_safe_alloc(C.ulong(cVKSize))
	if cVKPointer == nil {
		return []byte{}, &Error{functionName: "crypt_safe_alloc"}
	}
	defer C.crypt_safe_free(cVKPointer)

	err := C.crypt_volume_key_get(
		device.cryptDevice, C.int(keyslot),
		(*C.char)(cVKPointer), (*C.ulong)(unsafe.Pointer(&cVKSize)),
		cPassphrase, C.size_t(len(passphrase)),
	)
	if err < 0 {
		return []byte{}, &Error{functionName: "crypt_volume_key_get", code: int(err)}
	}
	return C.GoBytes(unsafe.Pointer(cVKPointer), C.int(cVKSize)), nil
}
```
Yeah, it's more correct to rename the function (e. g. DumpWithVolumeKey). However, I'm not sure where to place it. It's not a part of the library, thus, device.go doesn't seem to be the right place. Any suggestions?

**Comment by tracefinder** [comment]
@martinjungblut Hi, any news?

BTW, `crypt_safe_free` and `crypt_safe_alloc` were exported [quite recently](https://gitlab.com/cryptsetup/cryptsetup/-/merge_requests/63).

**Comment by martinjungblut** [comment]
@tracefinder Hi, sorry for the massive delay. First of all, thank you for using the project, I'm glad you find it useful.

I'm going to return to maintaining this project more actively, so I'll look into this issue tonight and get back to you.

**Comment by martinjungblut** [comment]
@tracefinder Hello again,
I've been thinking about your proposal, and I think having a subpackage for additional functionality could work really well.
Because it would use another namespace, code importing this subpackage would very clearly demarcate where it's being used.
I'm thinking a subpackage named `extensions`. As in "stuff here is an extension atop the original library".
What do you think? Thanks again!

**Comment by martinjungblut** [comment]
@tracefinder Oh and yes, the new `crypt_safe_free` and `crypt_safe_alloc` functions will come in very handy.

**Comment by tracefinder** [comment]
@martinjungblut Hi,
a subpackage sounds good to me. However, you'll need to export properties of `Device` structure as the `cryptDevice` property is used in `C.crypt_volume_key_get`.

**Comment by martinjungblut** [comment]
@tracefinder Hi,
Yeah, that makes sense. I'll get the code going and submit a PR having you as a reviewer, does that sound okay?
Thanks!

**Comment by tracefinder** [comment]
@martinjungblut Yeah, sounds great =)

**Comment by martinjungblut** [comment]
@tracefinder 
Hello again,
I got the code going last night, should open the PR soon.
But I have a question, I was checking the upstream code for `tcryptDump_with_volume_key`, as well as your implementation, and it looks like it's a nice wrapper around `crypt_volume_key_get`.

So I was thinking that maybe `Device` should expose that C function as a method? I think this was your original rationale.
Now, the C version requires us to provide two buffers and their sizes. But your implementation is a good abstraction, by returning a slice of bytes.

Do you have any more thoughts on this?

**Comment by tracefinder** [comment]
@martinjungblut
I just want to mention that I'm not a developer. So, if you see a better way of the implementation, it may really be better =)

> So I was thinking that maybe`Device` should expose that C function as a method?

I agree, it sounds reasonable. Thus, there is no need to expose `cryptDevice`.
If you wish to preserve the original behavior of `tcryptDump_with_volume_key`, we can use a pointer to a slice of bytes as parameter to the function. There are to paths to deal with `tcryptDump_with_volume_key` golang implementation:
* we can leave it as it is in my original snippet (except using `crypt_volume_key_get` as a `Device` method). In this case the return value (slice of bytes and error) differs from its C version (originally it returns unlocked key slot number or negative errno otherwise)
* we can return unlocked key slot number and error (as it happens in the original implementation). However, we'll need to pass a pointer to a slice of bytes, which is also different from the original implementation

In my opinion the second way is more versatile as it allows to get all values we can be interested in.

**Comment by martinjungblut** [comment]
@tracefinder Hello!

Ok, so I thought a bit more about it, invited you as a collaborator, and the PR is open: https://github.com/martinjungblut/go-cryptsetup/pull/6
Do let me know your honest thoughts on the PR review! I won't merge it until we both like the way it's written and working.

Again, thank you a lot for bringing this feature over, and telling me about `crypt_safe_alloc`/`crypt_safe_free`.

**Comment by tracefinder** [comment]
@martinjungblut Hi.
I'll take time to test it on the weekend. Many thanks!

**Comment by martinjungblut** [comment]
@tracefinder Hello.
Sure thing! I added you as a reviewer to the PR.
Thank you!
